"""
app/models/generated_invoice.py
────────────────────────────────
SQLAlchemy model for Klara AI-generated PDF invoices.

DISTINCT from loki_invoices (invoice_reminder.py):
  loki_invoices   — tracks externally-issued invoices for payment reminder purposes
  generated_invoices — invoices Klara AI creates from scratch (PDF generation)

Lifecycle:
  draft     → approved → sent → paid
                       ↘ cancelled (from any state)

The pdf_path column stores the absolute path on the Hetzner server.
GDPR: client PII is retained for legal invoicing obligations (§14 UStG — 10 years).
"""
from __future__ import annotations

import enum
from datetime import date, datetime
from decimal import Decimal
from uuid import uuid4

from sqlalchemy import Date, DateTime, Numeric, String, Text, func
from sqlalchemy.dialects.postgresql import UUID
from sqlalchemy.orm import Mapped, mapped_column

from klara.rarv.runtime import Base


class GeneratedInvoiceStatus(str, enum.Enum):
    draft     = "draft"      # generated, not yet approved
    approved  = "approved"   # Anthony approved, ready to send
    sent      = "sent"       # PDF emailed to client
    paid      = "paid"       # payment received
    cancelled = "cancelled"  # voided / written off


class GeneratedInvoice(Base):
    """
    Invoice generated by InvoiceGeneratorAgent.

    Identified by sequential invoice_number (INV-YYYY-NNNN, unique per year).
    Linked to a Lead via lead_id (optional — may be a standalone invoice).
    """
    __tablename__ = "generated_invoices"

    id: Mapped[str] = mapped_column(
        UUID(as_uuid=False), primary_key=True, default=lambda: str(uuid4())
    )

    # ── Ownership (optional lead link) ───────────────────────────────────────
    lead_id: Mapped[str | None] = mapped_column(String(36), nullable=True, index=True)

    # ── Invoice number ─────────────────────────────────────────────────────
    # Sequential: INV-YYYY-NNNN, unique across all years
    invoice_number: Mapped[str] = mapped_column(
        String(30), nullable=False, unique=True, index=True
    )

    # ── Client details (denormalised for legal record-keeping) ─────────────
    client_name:    Mapped[str]      = mapped_column(String(255), nullable=False)
    client_email:   Mapped[str]      = mapped_column(String(255), nullable=False, index=True)
    client_address: Mapped[str|None] = mapped_column(Text,        nullable=True)
    client_company: Mapped[str|None] = mapped_column(String(255), nullable=True)

    # ── Invoice content ────────────────────────────────────────────────────
    service_description: Mapped[str]     = mapped_column(Text,            nullable=False)
    amount_net:          Mapped[Decimal] = mapped_column(Numeric(10, 2),  nullable=False)
    vat_rate:            Mapped[Decimal] = mapped_column(Numeric(5, 2),   nullable=False, server_default="0.00")
    vat_amount:          Mapped[Decimal] = mapped_column(Numeric(10, 2),  nullable=False, server_default="0.00")
    amount_gross:        Mapped[Decimal] = mapped_column(Numeric(10, 2),  nullable=False)
    currency:            Mapped[str]     = mapped_column(String(3),       nullable=False, server_default="EUR")

    # ── Dates ──────────────────────────────────────────────────────────────
    issued_date: Mapped[date] = mapped_column(Date, nullable=False)
    due_date:    Mapped[date] = mapped_column(Date, nullable=False, index=True)

    # ── PDF artefact ───────────────────────────────────────────────────────
    # Absolute path on Hetzner: /root/loki-agents/invoices/INV-2026-0001.pdf
    pdf_path: Mapped[str | None] = mapped_column(Text, nullable=True)

    # ── Lifecycle ──────────────────────────────────────────────────────────
    status: Mapped[str] = mapped_column(
        String(20), nullable=False, server_default="draft", index=True
    )
    approval_id: Mapped[str | None] = mapped_column(String(36), nullable=True)
    sent_at:     Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    paid_at:     Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)

    # ── Audit ──────────────────────────────────────────────────────────────
    notes: Mapped[str | None] = mapped_column(Text, nullable=True)
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now(), nullable=False
    )
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now(), onupdate=func.now(),
        nullable=False
    )

    def __repr__(self) -> str:
        return (
            f"<GeneratedInvoice {self.invoice_number} "
            f"client={self.client_email} status={self.status}>"
        )
