"""
app/models/proposal.py
──────────────────────
Stores AI-generated IT consulting proposals.

Lifecycle:
  draft          → generated by ProposalDraftingAgent, stored here
  emailed        → emailed to consultant for review
  sent_to_client → consultant forwarded to client
  accepted       → client accepted the proposal
  declined       → client declined

Each Proposal is linked to the Lead and the ApprovalRequest that triggered it.
"""
import enum
import secrets
from datetime import datetime
from uuid import uuid4

from sqlalchemy import DateTime, Integer, String, Text, func
from sqlalchemy.dialects.postgresql import UUID
from sqlalchemy.orm import Mapped, mapped_column

from klara.rarv.runtime import Base


def _new_tracking_token() -> str:
    return secrets.token_urlsafe(32)


class ProposalStatus(str, enum.Enum):
    draft = "draft"
    emailed = "emailed"
    sent_to_client = "sent_to_client"
    accepted = "accepted"
    declined = "declined"


class Proposal(Base):
    __tablename__ = "proposals"

    id: Mapped[str] = mapped_column(
        UUID(as_uuid=False), primary_key=True, default=lambda: str(uuid4())
    )

    # ── Relationships ─────────────────────────────────────────────────────────
    lead_id: Mapped[str] = mapped_column(String(36), nullable=False, index=True)
    approval_id: Mapped[str | None] = mapped_column(String(36))   # triggering ApprovalRequest
    company: Mapped[str | None] = mapped_column(String(255))      # denormalised for quick display

    # ── Content ───────────────────────────────────────────────────────────────
    proposal_markdown: Mapped[str] = mapped_column(Text, nullable=False)
    tokens_used: Mapped[int | None] = mapped_column(Integer)

    # ── Status ────────────────────────────────────────────────────────────────
    status: Mapped[str] = mapped_column(
        String(30), default=ProposalStatus.draft, nullable=False, index=True
    )
    emailed_to: Mapped[str | None] = mapped_column(String(255))   # consultant email
    emailed_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True))

    # ── Engagement tracking (phase5-002) ──────────────────────────────────────
    # Set when phase5-002 sends the proposal to the client and the client
    # opens / clicks the embedded portal link.
    tracking_token: Mapped[str] = mapped_column(
        String(64), nullable=False, unique=True, index=True,
        default=_new_tracking_token,
    )
    sent_to_client_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True))
    opened_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True))
    last_opened_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True))
    first_clicked_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True))
    engagement_count: Mapped[int] = mapped_column(
        Integer, nullable=False, default=0, server_default="0"
    )

    # ── Timestamps ────────────────────────────────────────────────────────────
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now(), nullable=False
    )
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now(), onupdate=func.now(), nullable=False
    )

    def __repr__(self) -> str:
        return f"<Proposal id={self.id} lead_id={self.lead_id} status={self.status}>"
