"""
app/models/seo_content_post.py
──────────────────────────────
ORM model for SEO blog post drafts generated by SeoContentWriterAgent.

Records are created with status='pending_approval', then pushed to WordPress
as drafts. Anthony reviews and approves via the admin approval flow.

Table: seo_content_posts
"""
from datetime import datetime

from sqlalchemy import DateTime, Integer, String, Text, func
from sqlalchemy.orm import Mapped, mapped_column

from app.database import Base


class SeoContentPost(Base):
    __tablename__ = "seo_content_posts"

    id: Mapped[int] = mapped_column(Integer, primary_key=True, autoincrement=True)

    # ── Content ────────────────────────────────────────────────────────────────
    title_en: Mapped[str] = mapped_column(String(500), nullable=False)
    title_de: Mapped[str | None] = mapped_column(String(500))
    content_en: Mapped[str] = mapped_column(Text, nullable=False)
    content_de: Mapped[str | None] = mapped_column(Text)
    slug: Mapped[str] = mapped_column(String(200), nullable=False, unique=True, index=True)

    # ── Workflow status ────────────────────────────────────────────────────────
    # pending_approval → approved → published | rejected
    status: Mapped[str] = mapped_column(
        String(30), nullable=False, default="pending_approval", index=True
    )

    # ── WordPress integration ──────────────────────────────────────────────────
    wp_post_id: Mapped[int | None] = mapped_column(Integer)
    wp_draft_url: Mapped[str | None] = mapped_column(String(500))

    # ── Timestamps ────────────────────────────────────────────────────────────
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now(), nullable=False
    )
    updated_at: Mapped[datetime | None] = mapped_column(
        DateTime(timezone=True), onupdate=func.now()
    )
