//! G34.2a checkpoint 3 — Relay-mode peer connection via hbbr (TCP 21117).
//!
//! ## Why relay mode is the common case
//!
//! In the upstream rustdesk client (`vendor/rustdesk-ref/src/client.rs`),
//! when the rendezvous server (hbbs) decides the two peers cannot punch a
//! direct UDP tunnel — which is the normal outcome whenever either side
//! sits behind a symmetric NAT, corporate firewall, or carrier-grade NAT
//! — it routes the session through a relay (hbbr). For Klaravex's target
//! environment (small business + home users on consumer ISPs), relay mode
//! is what fires 95%+ of the time. Direct UDP punch is the optimisation,
//! relay is the default.
//!
//! ## Wire protocol
//!
//! The relay-mode flow has two distinct TCP connections:
//!
//!   1. **Client → hbbs (TCP 21116)**: send `RendezvousMessage::RequestRelay
//!      { id, uuid, relay_server, secure: false, licence_key }`. The hbbs
//!      forwards this to the customer's online rustdesk client, which
//!      decides whether to accept. hbbs eventually replies on this socket
//!      with `RendezvousMessage::RelayResponse { socket_addr, uuid, … }`
//!      indicating the relay endpoint we should dial.
//!
//!   2. **Client → hbbr (TCP 21117)**: open a NEW TCP socket to the relay
//!      and send `RendezvousMessage::RequestRelay { licence_key, id, uuid,
//!      conn_type }`. The relay holds the connection open and waits for
//!      the other side (the customer) to also connect with the same uuid;
//!      once both endpoints arrive, the relay just copies bytes between
//!      them. From this point the wire carries the peer-to-peer
//!      `Message::*` protobuf stream, NOT `RendezvousMessage::*`.
//!
//! ## Protocol provenance
//!
//! The two-stage flow is reproduced from
//! `vendor/rustdesk-ref/src/client.rs::request_relay` (lines 837-898) +
//! `create_relay` (lines 901-925). The wire framing is the same
//! `BytesCodec` varint length prefix used everywhere else in the
//! rendezvous protocol — both connections use the helper `encode_frame`
//! / `read_frame` from [`crate::relay`].
//!
//! ## What this module does NOT do
//!
//! - **NAT pre-warming UDP test_nat probe**: upstream does a TestNatRequest
//!   over UDP before issuing RequestRelay. Our `udp_rendezvous` heartbeat
//!   loop has already opened the outbound UDP NAT mapping by this point;
//!   the test_nat sequence is mostly for measuring NAT type, which we
//!   don't need to compute on the operator side.
//! - **`secure: true` flag**: when both sides have a token, upstream calls
//!   `secure_tcp` on the hbbs socket before sending `RequestRelay` so the
//!   token field is encrypted in transit. For the Klaravex unattended
//!   flow we always send `secure: false` (the token is unset).
//! - **`conn_type`**: defaults to `DEFAULT_CONN` (= 0). Service / file /
//!   port-forward modes are out of scope for the operator console.

use std::io::{self, Write};
use std::net::{TcpStream, ToSocketAddrs};
use std::time::Duration;

use protobuf::Message as _;

use crate::relay::{encode_frame, read_frame, HBBR_PORT, HBBS_MAIN_PORT};
use crate::rendezvous_proto::{
    rendezvous_message, ConnType, RelayResponse, RequestRelay, RendezvousMessage,
};

/// Result of a successful relay-mode session establishment. The TcpStream
/// is connected to the **relay** (hbbr 21117 on the configured host); the
/// caller's next step is to drive the peer-side secure handshake
/// (`Message::SignedId` → `Message::PublicKey`) over it.
#[derive(Debug)]
pub struct RelaySession {
    /// Connection to the hbbr relay. Read/write deadlines applied per
    /// `cfg.timeout`. Bytes flowing here are wrapped by the peer's
    /// `secure_connection` AEAD once the handshake completes.
    pub stream: TcpStream,
    /// Per-session uuid generated by us and sent in both RequestRelay
    /// messages so the relay can pair our connection with the customer's.
    pub uuid: String,
    /// Relay host:port we dialled (for logging / error reporting).
    pub relay_endpoint: String,
}

/// Errors returned by [`open_relay_session`].
#[derive(Debug)]
pub enum RelayError {
    Io(io::Error),
    /// hbbs replied to our RequestRelay with a refuse_reason — that's the
    /// customer-side rustdesk explicitly rejecting our connect.
    Refused(String),
    /// hbbs replied with a non-RelayResponse message — protocol mismatch
    /// or a transient version-skew bug.
    Protocol(String),
    /// hbbs did not reply at all within the deadline.
    Timeout,
}

impl std::fmt::Display for RelayError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Self::Io(e) => write!(f, "io: {e}"),
            Self::Refused(s) => write!(f, "refused: {s}"),
            Self::Protocol(s) => write!(f, "protocol: {s}"),
            Self::Timeout => write!(f, "timeout"),
        }
    }
}

impl std::error::Error for RelayError {}

impl From<io::Error> for RelayError {
    fn from(e: io::Error) -> Self {
        Self::Io(e)
    }
}

/// Open a relay-mode peer session.
///
/// ## Flow
///
/// 1. Generate a fresh uuid for this session (the relay uses this to
///    pair our TCP connection with the customer's).
/// 2. TCP connect to hbbs `host:21116`.
/// 3. Send `RendezvousMessage::RequestRelay { id, uuid, relay_server: "",
///    licence_key, secure: false }`.
/// 4. Wait for `RendezvousMessage::RelayResponse { relay_server, uuid,
///    refuse_reason }` on the same socket. If `refuse_reason` is
///    non-empty → [`RelayError::Refused`]. If `relay_server` is empty
///    we fall back to `host:21117`.
/// 5. Drop the hbbs socket. TCP connect to the relay endpoint.
/// 6. Send a SECOND `RendezvousMessage::RequestRelay { licence_key, id,
///    uuid, conn_type: DEFAULT_CONN }` on the relay socket.
/// 7. Return the relay socket as [`RelaySession::stream`].
///
/// On success the relay holds the socket open and copies bytes to/from
/// the customer-side connection (which the customer's rustdesk opens in
/// response to the hbbs forward). Subsequent traffic is the peer-to-peer
/// `Message::*` protocol.
pub fn open_relay_session(
    host: &str,
    peer_id: &str,
    licence_key: &str,
    timeout: Duration,
) -> Result<RelaySession, RelayError> {
    let uuid = generate_uuid_v4_string();
    eprintln!(
        "relay_client: open_relay_session id={peer_id} uuid={uuid} host={host}"
    );

    // Stage 1: hbbs → RequestRelay
    let relay_endpoint = ask_hbbs_for_relay(host, peer_id, &uuid, licence_key, timeout)?;

    // Stage 2: dial relay and send the second RequestRelay
    let relay_addr = parse_relay_endpoint(&relay_endpoint, host)?;
    let stream = dial_with_timeout(&relay_addr, timeout)?;
    send_relay_request_to_hbbr(&stream, peer_id, &uuid, licence_key)?;

    Ok(RelaySession {
        stream,
        uuid,
        relay_endpoint: relay_addr,
    })
}

/// First-stage: TCP to hbbs, send RequestRelay, parse RelayResponse.
fn ask_hbbs_for_relay(
    host: &str,
    peer_id: &str,
    uuid: &str,
    licence_key: &str,
    timeout: Duration,
) -> Result<String, RelayError> {
    let hbbs_endpoint = format!("{host}:{HBBS_MAIN_PORT}");
    let mut stream = dial_with_timeout(&hbbs_endpoint, timeout)?;

    let mut req = RequestRelay::new();
    req.id = peer_id.to_string();
    req.uuid = uuid.to_string();
    req.licence_key = licence_key.to_string();
    req.secure = false;
    // **Important**: include `relay_server: host`. The hbbs forwards
    // this RequestRelay verbatim to the customer-side rustdesk over
    // UDP. The customer then calls `connect_tcp(relay_server, ...)` to
    // dial the relay — if relay_server is empty, the customer attempts
    // a DNS lookup for "" and fails with "Name or service not known"
    // (observed in customer-side log during checkpoint 3 development).
    // Setting this to our hbbr host ensures the customer dials hbbr at
    // host:21117 and the relay pairs us up.
    req.relay_server = host.to_string();
    let mut out_msg = RendezvousMessage::new();
    out_msg.set_request_relay(req);
    let body = out_msg
        .write_to_bytes()
        .map_err(|e| RelayError::Protocol(format!("encode RequestRelay (hbbs): {e}")))?;
    let mut framed = Vec::with_capacity(body.len() + 4);
    encode_frame(&body, &mut framed)?;
    stream.write_all(&framed)?;
    stream.flush()?;

    // hbbs may send a few unrelated messages first (notably KeyExchange if
    // the server is configured for secure rendezvous). Loop until we see
    // a RelayResponse or the read times out.
    loop {
        let reply = match read_frame(&mut stream) {
            Ok(b) => b,
            Err(e)
                if e.kind() == io::ErrorKind::WouldBlock
                    || e.kind() == io::ErrorKind::TimedOut =>
            {
                return Err(RelayError::Timeout)
            }
            Err(e) => return Err(RelayError::Io(e)),
        };
        let msg = RendezvousMessage::parse_from_bytes(&reply)
            .map_err(|e| RelayError::Protocol(format!("decode hbbs reply: {e}")))?;
        match msg.union {
            Some(rendezvous_message::Union::RelayResponse(rr)) => {
                let rr: RelayResponse = rr;
                if !rr.refuse_reason.is_empty() {
                    return Err(RelayError::Refused(rr.refuse_reason.clone()));
                }
                let endpoint = if rr.relay_server.is_empty() {
                    format!("{host}:{HBBR_PORT}")
                } else {
                    // Some hbbs replies include only a host without port —
                    // upstream `check_port` defaults to 21117.
                    if rr.relay_server.contains(':') {
                        rr.relay_server.clone()
                    } else {
                        format!("{}:{}", rr.relay_server, HBBR_PORT)
                    }
                };
                return Ok(endpoint);
            }
            Some(rendezvous_message::Union::KeyExchange(_)) => {
                // hbbs is trying to set up a secure rendezvous channel —
                // skip and keep reading. For our unattended flow we don't
                // need encrypted RequestRelay because we don't carry a
                // token.
                continue;
            }
            Some(rendezvous_message::Union::ConfigureUpdate(_)) => {
                // Configuration push — ignore and keep reading.
                continue;
            }
            Some(rendezvous_message::Union::PunchHoleResponse(phr)) => {
                // Some hbbs versions reply with PunchHoleResponse-with-
                // relay_server instead of RelayResponse — treat the same.
                if !phr.relay_server.is_empty() {
                    let endpoint = if phr.relay_server.contains(':') {
                        phr.relay_server.clone()
                    } else {
                        format!("{}:{}", phr.relay_server, HBBR_PORT)
                    };
                    return Ok(endpoint);
                }
                return Err(RelayError::Protocol(
                    "hbbs returned PunchHoleResponse without relay_server".to_string(),
                ));
            }
            other => {
                return Err(RelayError::Protocol(format!(
                    "expected RelayResponse, got {:?}",
                    other.map(|v| std::mem::discriminant(&v))
                )));
            }
        }
    }
}

/// Second-stage: TCP to hbbr (already connected by caller via `stream`),
/// send `RequestRelay { licence_key, id, uuid, conn_type: 0 }`.
fn send_relay_request_to_hbbr(
    stream: &TcpStream,
    peer_id: &str,
    uuid: &str,
    licence_key: &str,
) -> Result<(), RelayError> {
    let mut req = RequestRelay::new();
    req.licence_key = licence_key.to_string();
    req.id = peer_id.to_string();
    req.uuid = uuid.to_string();
    // ConnType::DEFAULT_CONN — proto enum default is 0.
    req.conn_type = protobuf::EnumOrUnknown::new(ConnType::DEFAULT_CONN);
    let mut out_msg = RendezvousMessage::new();
    out_msg.set_request_relay(req);
    let body = out_msg
        .write_to_bytes()
        .map_err(|e| RelayError::Protocol(format!("encode RequestRelay (hbbr): {e}")))?;
    let mut framed = Vec::with_capacity(body.len() + 4);
    encode_frame(&body, &mut framed)?;
    let mut s = stream;
    s.write_all(&framed)?;
    s.flush()?;
    Ok(())
}

fn dial_with_timeout(endpoint: &str, timeout: Duration) -> io::Result<TcpStream> {
    let mut last_err: Option<io::Error> = None;
    for sa in endpoint.to_socket_addrs()? {
        match TcpStream::connect_timeout(&sa, timeout) {
            Ok(s) => {
                s.set_read_timeout(Some(timeout))?;
                s.set_write_timeout(Some(timeout))?;
                s.set_nodelay(true)?;
                return Ok(s);
            }
            Err(e) => last_err = Some(e),
        }
    }
    Err(last_err
        .unwrap_or_else(|| io::Error::new(io::ErrorKind::NotFound, "no addresses resolved")))
}

fn parse_relay_endpoint(endpoint: &str, fallback_host: &str) -> Result<String, RelayError> {
    if endpoint.is_empty() {
        return Ok(format!("{fallback_host}:{HBBR_PORT}"));
    }
    Ok(endpoint.to_string())
}

/// Generate a UUID-v4 hex string (no dashes — matches upstream `Uuid::new_v4()`
/// in `request_relay`, which uses `uuid::Uuid::new_v4().to_string()`).
/// We don't want to pull in the `uuid` crate just for this so we hash
/// random bytes into a 32-hex-char string.
fn generate_uuid_v4_string() -> String {
    use rand::RngCore;
    let mut buf = [0u8; 16];
    rand::thread_rng().fill_bytes(&mut buf);
    // Set version (4) and variant bits per RFC 4122
    buf[6] = (buf[6] & 0x0F) | 0x40;
    buf[8] = (buf[8] & 0x3F) | 0x80;
    let hex: String = buf.iter().map(|b| format!("{:02x}", b)).collect();
    format!(
        "{}-{}-{}-{}-{}",
        &hex[0..8],
        &hex[8..12],
        &hex[12..16],
        &hex[16..20],
        &hex[20..32],
    )
}

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

#[cfg(test)]
mod tests {
    use super::*;

    fn live_enabled() -> bool {
        std::env::var("KLX_LIVE_RELAY")
            .map(|v| !v.is_empty() && v != "0")
            .unwrap_or(false)
    }

    const LIVE_HOST: &str = "87.99.147.244";

    #[test]
    fn uuid_v4_format() {
        let u = generate_uuid_v4_string();
        // Standard length: 8-4-4-4-12 + 4 dashes = 36
        assert_eq!(u.len(), 36);
        let parts: Vec<&str> = u.split('-').collect();
        assert_eq!(parts.len(), 5);
        assert_eq!(parts[0].len(), 8);
        assert_eq!(parts[1].len(), 4);
        assert_eq!(parts[2].len(), 4);
        assert_eq!(parts[3].len(), 4);
        assert_eq!(parts[4].len(), 12);
        // Version 4 → 13th hex digit must be '4'
        assert_eq!(&u[14..15], "4");
    }

    /// **LIVE TEST**: requesting a relay session for a deliberately
    /// unknown peer id should produce a structured error — either
    /// `Refused` (customer-side rustdesk would have to be online to
    /// reject) or `Timeout` (hbbs forwards and waits, nothing comes
    /// back). Both prove the wire format works end-to-end.
    #[test]
    fn relay_session_unknown_peer_live() {
        if !live_enabled() {
            eprintln!("relay_session_unknown_peer_live: skipped");
            return;
        }
        let licence = crate::secure::SERVER_PUBKEY_BASE64;
        let peer_id = format!("klx-ckpt3-unknown-{}", std::process::id());
        let result = open_relay_session(
            LIVE_HOST,
            &peer_id,
            licence,
            Duration::from_millis(3000),
        );
        eprintln!("relay_session_unknown_peer_live: {result:?}");
        match result {
            Err(RelayError::Refused(_))
            | Err(RelayError::Timeout)
            | Err(RelayError::Protocol(_))
            | Err(RelayError::Io(_)) => {
                // Any structured error is acceptable — proves we round-
                // tripped a RequestRelay protobuf and either hbbs or the
                // (absent) customer replied or timed out cleanly.
            }
            Ok(session) => {
                // Possible if hbbs is configured to always grant relay
                // regardless of customer presence. In that case the
                // session is "half-open" — the relay is holding our
                // socket waiting for a customer that will never arrive.
                eprintln!(
                    "relay_session: unexpectedly succeeded for unknown peer, endpoint={}",
                    session.relay_endpoint
                );
            }
        }
    }
}
