#!/usr/bin/env bash
# wire-rarv-env.sh — copy secrets into Klaravex2.0/klara/rarv/.env.rarv (gitignored).
# Logs var NAMES only. Does not install systemd units.
set -euo pipefail

WORKER_ENV="${WORKER_ENV:-/home/anthony/klaravex/infra/docker-services/worker/.env}"
TARGET="${TARGET:-/home/anthony/Klaravex2.0/klara/rarv/.env.rarv}"
EXAMPLE="/home/anthony/Klaravex2.0/klara/rarv/.env.rarv.example"

[[ -f "$WORKER_ENV" ]] || { echo "ERROR: missing $WORKER_ENV" >&2; exit 1; }

get() {
  # Avoid pipefail+SIGPIPE from head closing early on a match
  local line
  line="$(grep -E "^${1}=" "$WORKER_ENV" 2>/dev/null | head -1 || true)"
  [[ -n "$line" ]] && echo "${line#*=}"
}

DB_URL="$(get DATABASE_URL)"
# Host-side runner uses 127.0.0.1 tunnel, not host.docker.internal
DB_URL="${DB_URL//@host.docker.internal:15432/@127.0.0.1:15432}"
DB_URL="${DB_URL/postgresql:\/\//postgresql+asyncpg:\/\/}"
[[ "$DB_URL" == postgresql+asyncpg://* ]] || DB_URL="postgresql+asyncpg://${DB_URL#postgresql://}"

LITELLM_KEY="$(get LITELLM_API_KEY)"; [[ -z "$LITELLM_KEY" ]] && LITELLM_KEY="$(get LITELLM_KEY)"
LITELLM_URL="$(get LITELLM_BASE_URL)"; [[ -z "$LITELLM_URL" ]] && LITELLM_URL="$(get LITELLM_URL)"
[[ -z "$LITELLM_URL" ]] && LITELLM_URL="http://127.0.0.1:8000"
# Container-internal URLs won't work from host systemd — rewrite
LITELLM_URL="${LITELLM_URL//litellm:4000/127.0.0.1:8000}"
LITELLM_URL="${LITELLM_URL//klaravex-llm-gateway:4000/127.0.0.1:8000}"
LITELLM_URL="${LITELLM_URL//host.docker.internal/127.0.0.1}"

GH_TOKEN="$(get GITHUB_VAULT_TOKEN)"
if [[ -z "$GH_TOKEN" || "$GH_TOKEN" == REPLACE* ]]; then
  if command -v gh >/dev/null 2>&1; then
    GH_TOKEN="$(gh auth token 2>/dev/null || true)"
  fi
fi

{
  echo "# Generated by wire-rarv-env.sh $(date -Iseconds) — DO NOT COMMIT"
  echo "DATABASE_URL=${DB_URL}"
  echo "DB_SCHEMA=$(get DB_SCHEMA || echo klaravex)"
  echo "GITHUB_VAULT_TOKEN=${GH_TOKEN}"
  echo "GITHUB_VAULT_REPO=$(get GITHUB_VAULT_REPO)"
  echo "GITHUB_VAULT_BRANCH=$(get GITHUB_VAULT_BRANCH)"
  echo "LITELLM_BASE_URL=${LITELLM_URL}"
  echo "LITELLM_API_KEY=${LITELLM_KEY}"
  echo "OPENAI_API_KEY=$(get OPENAI_API_KEY)"
  echo "ANTHROPIC_API_KEY=$(get ANTHROPIC_API_KEY)"
  echo "VAULT_PATH=/home/anthony/.claude/knowledge/klaravex-vault"
  echo "APP_ENV=production"
  echo "APP_DEBUG=false"
} > "$TARGET"

chmod 600 "$TARGET"
echo "[wire-rarv-env] wrote var names: DATABASE_URL DB_SCHEMA GITHUB_VAULT_* LITELLM_* OPENAI_API_KEY ANTHROPIC_API_KEY VAULT_PATH"
echo "[wire-rarv-env] target=$TARGET mode=600"
